# Generated by Django 5.0.6 on 2024-05-20 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_course_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.group'),
        ),
    ]
