# Generated by Django 5.0.6 on 2024-05-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_course_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='attended_hours',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
